// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	paymentv1 "order/internal/client/grpc/payment/v1"

	mock "github.com/stretchr/testify/mock"

	v1 "order/internal/client/grpc/inventory/v1"
)

// Clients is an autogenerated mock type for the Clients type
type Clients struct {
	mock.Mock
}

// Inventory provides a mock function with no fields
func (_m *Clients) Inventory() v1.InventoryClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Inventory")
	}

	var r0 v1.InventoryClient
	if rf, ok := ret.Get(0).(func() v1.InventoryClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.InventoryClient)
		}
	}

	return r0
}

// Payment provides a mock function with no fields
func (_m *Clients) Payment() paymentv1.PaymentClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Payment")
	}

	var r0 paymentv1.PaymentClient
	if rf, ok := ret.Get(0).(func() paymentv1.PaymentClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(paymentv1.PaymentClient)
		}
	}

	return r0
}

// NewClients creates a new instance of Clients. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClients(t interface {
	mock.TestingT
	Cleanup(func())
}) *Clients {
	mock := &Clients{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
