// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// PaymentClient is an autogenerated mock type for the PaymentClient type
type PaymentClient struct {
	mock.Mock
}

// PayOrder provides a mock function with given fields: ctx, orderUUID, method
func (_m *PaymentClient) PayOrder(ctx context.Context, orderUUID string, method int32) (string, error) {
	ret := _m.Called(ctx, orderUUID, method)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int32) (string, error)); ok {
		return rf(ctx, orderUUID, method)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int32) string); ok {
		r0 = rf(ctx, orderUUID, method)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int32) error); ok {
		r1 = rf(ctx, orderUUID, method)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPaymentClient creates a new instance of PaymentClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentClient {
	mock := &PaymentClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
